PS C:\Users\pacha\Desktop\SAE_pacman_iuto\source> python3 .\test_plateau.py
..............E
======================================================================
ERROR: test_prochaine_intersection (__main__.test_case.test_prochaine_intersection)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\pacha\Desktop\SAE_pacman_iuto\source\test_plateau.py", line 425, in test_prochaine_intersection
    res=plateau.prochaine_intersection(p2,pos,dir)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pacha\Desktop\SAE_pacman_iuto\source\plateau.py", line 546, in prochaine_intersection
    truc = directions_possibles(plateau,pos_actuelle)
                                        ^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'pos_actuelle' where it is not associated with a value

----------------------------------------------------------------------
Ran 15 tests in 0.016s

FAILED (errors=1)
PS C:\Users\pacha\Desktop\SAE_pacman_iuto\source> 